routes/web.php
<?php

use App\Http\Controllers\AnalyticsController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\DeleteUserController;
use App\Http\Controllers\EmailController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\HomePageController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

Route::auth();

Route::group(['middleware' => 'is_guest'], function() {

Route::resource('/analytics', AnalyticsController::class);

// Route for profile page
Route::get('/profile', [HomeController::class, 'profile'])->name('profile-index');

// Route for logout
Route::get('/logout', [LoginController::class, 'logout']);

// Route for create-blog page
Route::get('/create-blog', [PostController::class, 'createblog'])->name('createblog');

// Route for User Settings Page
Route::get('/profile-settings', [UserController::class, 'settings'])->name('user.settings');

// Routes for DASHBOARD pages

Route::resource('/users', UserController::class, [
    'names' => [
      ],
]);
Route::resource('/posts', PostController::class, [
    'names' => [
      ],
]);
});

// This return /homepage
Route::get('/', [HomeController::class, 'redirect']);

// Route for main homepage
Route::get('/homepage', [HomeController::class, 'index'])->name('homepage');

// Route for contact page
Route::get('/contact-me', [HomeController::class, 'contact'])->name('contact-me');
// 
// Route for about page
Route::get('/about-me', [HomeController::class, 'about'])->name('about-me');

// Route for post page
Route::get('/post/{slug}', [HomePageController::class, 'show'])->name('post-index');

// Routes for contact page email
Route::get('/email', [EmailController::class, 'create']);
Route::post('/email', [EmailController::class, 'sendEmail'])->name('send.email');

Route::get('/contactlist', [[DeleteUserController::class, 'contactlist']]);

Route::post('multipleusersdelete', [DeleteUserController::class, 'multipleusersdelete']);

Route::get('/info/{id}', [UserController::class, 'show'])->name('custom.show');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

use Cviebrock\EloquentSluggable\Sluggable;
use Cviebrock\EloquentSluggable\SluggableScopeHelpers;


class Post extends Model
{


    use HasFactory;

    // Sluggable
    use Sluggable;
    use SluggableScopeHelpers;  

    protected $path = '/storage/images/';
    
    public function getPictureAttribute($file) {
        return $this->path . $file;
    }


    // To make sure that everything is fillable
    protected $guarded = [];

    // No timestamps while registering
    public $timestamps = false;

    // Relationship with users table
    public function user() {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => ['title'],
                'onUpdate' => true,
            ]
        ];
    }

    

    

}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Post;
use Illuminate\Support\Facades\Auth;

use App\Http\Requests\PostRequest;
use App\Models\User;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $posts = Post::paginate(8);
        $auth_user = auth()->user();

        // For Profile Card
        $user = auth()->user();

        return view('dashboard.posts.posts', compact(
            'posts',
            'auth_user',
            'user',
        ));
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostRequest $request)
    {
        $input = $request->all();
        $user = Auth::user();   
        
        if ($file = $request->file('picture')) {
            $name = time() . $file->getClientOriginalName();
            $file->move('storage/images', $name);
            $input['picture'] = $name; 
            $input['random'] = 'no-picture';
        } else {
            $input['picture'] = 'no-picture';
            $input['random'] = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUnvISVTYopMAy17o3mB2lfSPeEjoKfAdV2w&usqp=CAU";
        }
  
        if(isset($user)) {
        $user->posts()->create($input);
        session()->flash('success', 'Blog post successfully published!!');
        } else {
        session()->flash('failure', 'Blog posting failed!');
        }

        return to_route('homepage')->withFragment('#blog-published');
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        
        // $post = Post::findBySlug($slug);

        // return view('dashboard.posts.posts_show', compact(
        //     'post',
        // ));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::findBySlug($id);

        return view('dashboard.posts.posts_edit', compact(
            'post',
        ));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input = $request->all();
    
        if ($file = $request->file('picture')) {
            $name = time() . $file->getClientOriginalName();
            $file->move('storage/images', $name);
            $input['picture'] = $name;

        }

        if (auth()->user()->admin == 'true' || auth()->user()->admin == 'TRUE') {
            $post = Post::findOrFail($id)->whereId($id)->first()->update($input);
        } else {
            auth()->user()->posts()->whereId($id)->first()->update($input);
        }

        session()->flash('success-edit', 'You successfully edited this blog!');
            
        return redirect()->route('posts.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::findOrFail($id);
        $post->delete();
        session()->flash('delete-post', 'The post has been successfully deleted...');

        return redirect('/posts');
    }

    
    public function createblog() {
        return view('pages.create_blog');
    }


}

resources/views/dashboard/posts/posts.blade.php
@extends('pages.profile_page')

<x-titles.posts_title></x-titles.posts_title>

@section('content')

@if(session()->has('success-edit'))
<div 
style="margin-top: 30px;"
class="alert alert-success">
{{ session()->get('success-edit') }}
</div>
@endif


@if(session()->has('delete-post'))
<div 
style="margin-top: 30px;"
class="alert alert-danger">
{{ session()->get('delete-post') }}
</div>
@endif


@if (auth()->user()->admin == 'true' || auth()->user()->admin == 'TRUE')


<div class="container">


@if (count($posts) > 0)

@foreach ($posts as $post)

              <div class="col-xs-12 col-md-3">
                  <div class="color-block-wrapper">
                      <div class="color-block color-block-lblue">
    
                              {{$post->title}}
                     
                          <div class="color-block-text">
                               {{$post->short_description}}
                          </div>
            
                          <img 
            style="border-radius: 10px;margin-top: 5px"
            height="140"
            width="100"
            
            @if ($post->picture == '/storage/images/no-picture')

            src="{{$post->random}}" 
                

            @else 

            src="{{$post->picture}}" 

            @endif

            alt="Not Available"
            title="Not Available">
        
                      </div>
                      
              <div class="color-block-bottom">

              <a href="{{route('post-index',$post->slug)}}" class="btn btn-transparent-lblue">Show this post
              </a>

              <a 
              style="margin-top: 10px" 
              href="{{route('posts.edit', $post->slug)}}" 
              class="btn btn-primary2">Edit this post
            </a>

              </div>
    

                  </div>
              </div>

@endforeach

@else 

<div class="dashboard-div">
    <h3>There are no posts right now at the moment.</h3>
</div>
    
@endif

@else 


@if(count($auth_user->posts) > 0)

@foreach ($auth_user->posts as $post)


<div class="col-xs-12 col-md-3">
    <div class="color-block-wrapper">
        <div class="color-block color-block-lblue">

                {{$post->title}}
       
            <div class="color-block-text">
                 {{$post->short_description}}
            </div>

            <img 
            style="border-radius: 10px;margin-top: 5px"
            height="140"
            width="100"
            
            @if ($post->picture == '/storage/images/no-picture')

            src="{{$post->random}}" 
                

            @else 

            src="{{$post->picture}}" 

            @endif

            alt="Not Available"
            title="Not Available">
          
        </div>
        
<div class="color-block-bottom">

<a href="{{route('post-index',$post->slug)}}" class="btn btn-transparent-lblue">Show this post
</a>

<a 
style="margin-top: 10px" 
href="{{route('posts.edit', $post->slug)}}" 
class="btn btn-primary2">Edit this post
</a>

</div>


    </div>
</div>
   

    @endforeach


@else

<div class="dashboard-div">
    <h3>You don't have any posts at the moment...</h3>
</div>

@endif

</div> 


@endif



@endsection




@section('pagination')

<div class="row">
    <center>{{$posts->links('pagination::bootstrap-4')}}</center>
</div> 
    
@endsection

resources/views/dashboard/posts/posts_edit.blade.php
@extends('pages.profile_page')

@section('content')



    <div 
    class="dashboard-div" 
    style="margin-left: 0;margin-bottom: 20px">
        <h3>Edit Post: {{$post->title}}</h3>
    </div>




    {!! Form::model($post, ['method' => 'PATCH', 'action' => ['App\Http\Controllers\PostController@update', $post->id], 'files' => true]) !!}


    <div class="form-group" style="width: 350px">
        {!! Form::label('title', 'Title:', ['class' => 'mb-2']) !!}
        {!! Form::text('title', null, ['class' => 'form-control']) !!}
    </div>

    <div class="form-group" style="width: 350px">
        {!! Form::label('short_description', 'Short Description:', ['class' => 'mb-2']) !!}
        {!! Form::text('short_description', null, ['class' => 'form-control']) !!}
    </div>

    
    <div style="width: 40%;margin-bottom: 30px">
        {!! Form::label('content', 'Content:') !!}
    {{   Form::textarea('content', null, ['class' => 'form-control',
        'rows'       => 1, 
        'name'       => 'content',
        'id'         => 'myeditorinstance',
    ]) }}
    </div>
</div>

<br><br><br><br>

    <div class="form-group" style="width: 350px">
        {!! Form::label('picture', 'Picture:', ['class' => 'mb-2']) !!}
        {!! Form::file('picture', null, ['class' => 'form-control']) !!}
    </div>
    

    {!! Form::submit('Save', ['class' => 'btn btn-primary button-hover']) !!} 


    {!! Form::close() !!}

        <div style="margin-top: 20px;margin-bottom: 20px">
            {!! Form::open(['method' => 'DELETE', 'action' => ['App\Http\Controllers\PostController@destroy', $post->id]]) !!}

        <div 
        style="margin-top: 15px"
        class="text-primary">

           {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}

  
        </div>
        
        {!! Form::close() !!}

        </div>

      


    
@endsection