routes/web.php
<?php

use App\Http\Controllers\AnalyticsController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\DeleteUserController;
use App\Http\Controllers\EmailController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\HomePageController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

Route::auth();

Route::group(['middleware' => 'is_guest'], function() {

Route::resource('/analytics', AnalyticsController::class);

// Route for profile page
Route::get('/profile', [HomeController::class, 'profile'])->name('profile-index');

// Route for logout
Route::get('/logout', [LoginController::class, 'logout']);

// Route for create-blog page
Route::get('/create-blog', [PostController::class, 'createblog'])->name('createblog');

// Route for User Settings Page
Route::get('/profile-settings', [UserController::class, 'settings'])->name('user.settings');

// Routes for DASHBOARD pages

Route::resource('/users', UserController::class, [
    'names' => [
      ],
]);
Route::resource('/posts', PostController::class, [
    'names' => [
      ],
]);
});

// This return /homepage
Route::get('/', [HomeController::class, 'redirect']);

// Route for main homepage
Route::get('/homepage', [HomeController::class, 'index'])->name('homepage');

// Route for contact page
Route::get('/contact-me', [HomeController::class, 'contact'])->name('contact-me');
// 
// Route for about page
Route::get('/about-me', [HomeController::class, 'about'])->name('about-me');

// Route for post page
Route::get('/post/{slug}', [HomePageController::class, 'show'])->name('post-index');

// Routes for contact page email
Route::get('/email', [EmailController::class, 'create']);
Route::post('/email', [EmailController::class, 'sendEmail'])->name('send.email');

Route::get('/contactlist', [[DeleteUserController::class, 'contactlist']]);

Route::post('multipleusersdelete', [DeleteUserController::class, 'multipleusersdelete']);

Route::get('/info/{id}', [UserController::class, 'show'])->name('custom.show');

resources/views/layouts/includes/admin_nav.blade.php
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    

    {{-- ADMIN TOP NAVIGATION --}}
    @include('layouts.includes.admin_top_nav')


    {{-- ADMIN SIDE NAVIGATION --}}
    @include('layouts.includes.admin_side_nav')



    <!-- /.navbar-static-side -->
</nav>

resources/views/layouts/includes/admin_side_nav.blade.php
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li class="sidebar-search">
                <div class="input-group custom-search-form">
                    <input type="text" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                </div>
                <!-- /input-group -->
            </li>
            <li>
                <a href="{{route('profile-index')}}"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
            </li>

            <li>
                <a href="#"><i class="fa fa-wrench fa-fw"></i>Posts<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="{{route('posts.index')}}">All Posts</a>
                    </li>


                </ul>
                <!-- /.nav-second-level -->
            </li>

            <li>
                <a href="#"><i class="fa fa-wrench fa-fw"></i> Users<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="{{route('users.index')}}">All Users</a>
                    </li>


                </ul>
                <!-- /.nav-second-level -->
            </li>


            <li>
                <a href="#"><i class="fa fa-wrench fa-fw"></i>Analytics<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="{{route('analytics.index')}}">Show Analytics</a>
                    </li>


                </ul>
                <!-- /.nav-second-level -->
            </li>
            

       
        </ul>


    </div>
    
    <!-- /.sidebar-collapse -->
</div>

resources/views/layouts/includes/admin_top_nav.blade.php
<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    
    <a style="margin-left: 5px;" class="navbar-brand" href="{{route('homepage')}}">
        <img height="30" src="https://media.istockphoto.com/photos/silhouette-of-profile-guy-in-shirt-with-white-button-in-aqua-menthe-picture-id1206439390?k=20&m=1206439390&s=170667a&w=0&h=wDX4xov95UOzjOgOkTqRurDiTepjhqAA7Q2iFofrO5c=" alt="">
    </a>
    
</div>
<!-- /.navbar-header -->



{{-- TOP NAVIGATION --}}
<ul class="nav navbar-top-links navbar-right">


    <!-- /.dropdown -->
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            
            <i class="fa fa-user fa-fw"></i>

            <span> {{Auth::user()->name}}</span>

            
            <i class="fa fa-caret-down ml-5"></i>
            
        </a>
        <ul class="dropdown-menu dropdown-user">
            <li><a href="{{route('users.show', $user->id)}}"><i class="fa fa-user fa-fw"></i> Profile</a>
            </li>
            <li><a href="{{route('user.settings')}}"><i class="fa fa-gear fa-fw"></i> Settings</a>
            </li>
            <li class="divider"></li>
            <li><a href="{{url('/logout')}}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
            </li>
        </ul>
        <!-- /.dropdown-user -->
    </li>
    <!-- /.dropdown -->


    
</ul>

resources/views/layouts/includes/profile_page_content_section.blade.php
@extends('pages.profile_page')

@section('content')

<style>
 
 @media only screen and (max-width: 1200px) {  
    .potd {
    width: 250px;
    height: auto;
  }
}



</style>

<div class="dashboard-div">
    <h3>Welcome back {{auth()->user()->name}}!</h3>
 </div>

 <div class="dashboard-div-second">
 <h5>Photo of the day:</h4>

 <img 
 class="potd"
 style="border-radius: 10px"
 width="450"
 height="300"
 src="https://source.unsplash.com/random" 
 alt="">
 
</div>
    
@endsection